default_platform(:android)

platform :android do
  desc "Build the AAB"
  lane :build do |options|
    #if options[:bump] != "false"
    #  increment_version_code(app_project_dir: "android/app")
    #  increment_version_name(app_project_dir: "android/app", bump_type: "patch")
    #end
    gradle(task: "bundleRelease", project_dir: "android")
  end

  desc "Build production APK"
lane :build_apk do
  gradle(
    task: "assemble",
    build_type: "Release",
    project_dir: "android"
  )
end

desc "Build debug APK"
lane :build_debug do
  gradle(
    task: "assemble",
    build_type: "Debug",
    project_dir: "android"
  )
end


desc "Build and install debug APK on emulator"
lane :install_debug do
  gradle(
    task: "assemble",
    build_type: "Debug",
    project_dir: "android"
  )

  adb(
    command: "install -r android/app/build/outputs/apk/debug/app-debug.apk"
  )
end

desc "Build and install APK on emulator"
lane :install_emulator do
  # Build the APK first
  gradle(
    task: "assemble",
    build_type: "Release",
    project_dir: "android"
  )

  # Install on all connected devices/emulators
  adb(
    command: "install -r android/app/build/outputs/apk/release/app-release.apk"
  )
end

  desc "Deploy to Internal Testing"
  lane :deploy do
    build
    upload_to_play_store(
      track: "internal",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
    )
  end

  desc "Alias for deploy"
  lane :beta do
    deploy
  end
end
